// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

package prueba1

import "github.com/iotaledger/wasp/packages/vm/wasmlib/go/wasmlib"

const (
	ScName        = "prueba1"
	ScDescription = "prueba1 description"
	HScName       = wasmlib.ScHname(0xf0666408)
)

const (
	ParamOwner = "owner"
	ParamRes   = "res"
)

const (
	ResultOwner = "owner"
	ResultRes   = "res"
)

const (
	StateOwner = "owner"
	StateText  = "text"
)

const (
	FuncInit     = "init"
	FuncSetOwner = "setOwner"
	FuncSetText  = "setText"
	ViewGetOwner = "getOwner"
	ViewGetText  = "getText"
)

const (
	HFuncInit     = wasmlib.ScHname(0x1f44d644)
	HFuncSetOwner = wasmlib.ScHname(0x2a15fe7b)
	HFuncSetText  = wasmlib.ScHname(0xdbd4a095)
	HViewGetOwner = wasmlib.ScHname(0x137107a6)
	HViewGetText  = wasmlib.ScHname(0xf76eceee)
)
