// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

package prueba1

import "github.com/iotaledger/wasp/packages/vm/wasmlib/go/wasmlib"

const (
	IdxParamOwner = 0
	IdxParamRes   = 1

	IdxResultOwner = 2
	IdxResultRes   = 3

	IdxStateOwner = 4
	IdxStateText  = 5
)

const keyMapLen = 6

var keyMap = [keyMapLen]wasmlib.Key{
	ParamOwner,
	ParamRes,
	ResultOwner,
	ResultRes,
	StateOwner,
	StateText,
}

var idxMap [keyMapLen]wasmlib.Key32
